// Action type constants
export const LOAD_LEVEL = 'LOAD_LEVEL';
export const APPLY_FIX = 'APPLY_FIX';
export const WRONG_CLICK = 'WRONG_CLICK';
export const GET_HINT = 'GET_HINT';
export const POST_CHAT_MESSAGE = 'POST_BUDDY_MESSAGE';
export const RESET_PROGRESS = 'RESET_PROGRESS';
export const TOGGLE_NOTEBOOK = 'TOGGLE_NOTEBOOK';
export const NEXT_LEVEL = 'NEXT_LEVEL';
export const CODE_CLICK = 'CODE_CLICK';
export const SET_TYPING_ANIMATION_COMPLETE = 'SET_TYPING_ANIMATION_COMPLETE';

// Authentication action types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// Player statistics action types
export const UPDATE_LEVEL_STATS = 'UPDATE_LEVEL_STATS';
export const SET_PLAYER_STATS = 'SET_PLAYER_STATS';

// Group management action types
export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE';
export const FETCH_GROUPS_REQUEST = 'FETCH_GROUPS_REQUEST';
export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS';
export const FETCH_GROUPS_FAILURE = 'FETCH_GROUPS_FAILURE';
export const SELECT_GROUP = 'SELECT_GROUP';
export const FETCH_GROUP_BY_ID_REQUEST = 'FETCH_GROUP_BY_ID_REQUEST';
export const FETCH_GROUP_BY_ID_SUCCESS = 'FETCH_GROUP_BY_ID_SUCCESS';
export const FETCH_GROUP_BY_ID_FAILURE = 'FETCH_GROUP_BY_ID_FAILURE';
export const UPDATE_GROUP_NAME_REQUEST = 'UPDATE_GROUP_NAME_REQUEST';
export const UPDATE_GROUP_NAME_SUCCESS = 'UPDATE_GROUP_NAME_SUCCESS';
export const UPDATE_GROUP_NAME_FAILURE = 'UPDATE_GROUP_NAME_FAILURE';
export const TOGGLE_JOIN_CODE_ACTIVE_REQUEST = 'TOGGLE_JOIN_CODE_ACTIVE_REQUEST';
export const TOGGLE_JOIN_CODE_ACTIVE_SUCCESS = 'TOGGLE_JOIN_CODE_ACTIVE_SUCCESS';
export const TOGGLE_JOIN_CODE_ACTIVE_FAILURE = 'TOGGLE_JOIN_CODE_ACTIVE_FAILURE';
export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAILURE = 'DELETE_GROUP_FAILURE';
