name: Test and Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies (web)
        run: |
          cd web
          npm ci

      - name: Install dependencies (levels_compiler)
        run: |
          cd levels_compiler
          npm ci

      - name: Run tests
        run: |
          cd web
          npm run test

      - name: Build project
        run: |
          cd web
          npm run build

      - name: Deploy to Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"
